dist: trusty
language: node_js
node_js:
- '11'
branches:
  only:
  - master
  - "/^v.*$/"
addons:
  apt:
    packages:
      - xvfb
install:
    - npm install -g xvfb-maybe
before_script:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    - npm install --quiet -g gulp
    - npm install
script:
    - npm run build
    - xvfb-maybe ./node_modules/karma/bin/karma start karma.conf.js --single-run
before_deploy:
    - npm run prerelease
deploy:
  - provider: releases
    skip_cleanup: true
    email: alexander_veit@hms.harvard.edu
    api_key:
      secure: dTQFJowOLRZvB+jppUGrVTh/8H6HKOrb1HyZLc6ST1vpmJAvdMVfDmr/HXuU7je+aeD5pXSwcqDF5xHVR7NQogx2XzY/N1uCRP7tpTldyIIAe0BxHdWfvNAMLNqjZAioAAV7+j5zfDBPcgg6OETs2Pgg6xHBGj8lCjJ0zv103blpvAiXjSSXfIkT0JXh5aWbSMv3anMeQzggzqiFFTCVZhYExrBUMgdR6hFOxVJTxK2HTd+4OOMLTOgrJL+dSWmWcmlFHG+XotTTp9bUJjuZOWo7MR6roqFIgI+U5GqK8gFSn1Eh7B6z2ZmVfBF+HwL/912P+/aXB5HW1h2B5KfFQaL+DUq7HJ3rlrAiDvy+Bx0tRSOi3Gm+VaSYjghWv5AkGnH8BgyRjmAdCz/8SLTc/FERKtkbkhPJOmYlLwhjs7IeK/eYhZLGjtx1gTih43Uwvd2O5fSDrWxQ3Ut4j402WOaAKe6EOcUEi4OXBzrNikv+BUp++wqmL/XUK1qgZRjcoYnUjul2h3t1JPIWb2bJ2uzu12gx7QpspiGqjXeDI1y0g7pd9lieL0TGVUQfeEI+8K5VgYuJxg28tEN0R1G3iLr1/edzM5q6QZO5NZptkwgYKLuCmd6G4J48hddv2pGo5M8ghzrhwByj8LAwk2uU6lhjqsy3B7u7McxZTSrFqSY=
    file: dist.zip
    on:
      tags: true
      branch: master
      repo: higlass/higlass-orthologs
  - provider: npm
    skip_cleanup: true
    email: alexander_veit@hms.harvard.edu
    api_key:
      secure: I3jpKAgC9UTVieNrTLmFXw0KKg+BeMxAiXaxBLpXhtI2GAEkRJQcg0pV3IpV+cM/BVJQE/dHPUqMHmuLdL9ayDgbwUoboZeHdd9hIMAtJtOoX2opaPLbsEqz1LTn6jDYH8cb8f3XTDyG4xDi5gyqqT194P1YldcY1yYuQbgsxq8RJNkfHPZrr0PPkEishwOKdl6dPGG1YLY9SRpZDkDHvcFjKJ6Uo1JVYPOvrFQgcKJVezfxT2PsplL3BerhM27TG6uSaahg8iL70cOepwIj0wb0eW6E38CtXUDUdTUv35KVGoalqWrDjfdKyRbXe+oPgeNNEm5T9od9929qwdFtDCilyE9pQIqoJIyaKhRxLXdk/4+R7MfkIefTg0/8Fqz2FlPfYijXaaJrmA5VOgLKHFZQdgGNPymnwg/B6eVFuphvoWtN+WGgv+IhgNw5GB1DlsOWDCJHKFVdOwFYHwLYUfkgUpZd2lMkdKftmKWZnfg+pFJargiRxQ2vlIV4b0/09JlB6QdDxMRRq/BotyyDVgZNyHKy+n/jno1ZSlkmYfpKS/jglV9gnkUj75AnLFzdfG/Vldj+TEMBI2cnZrPmW21SOKks//WoW3GYhzaCGb/147zRrLXnRSpO1wPahd4u8N/0tKcjXXJLRW0re1U01zSEn++J/4d0x5A0cUPfOBs=
    on:
      tags: true
      branch: master
      repo: higlass/higlass-orthologs
